injector:
  enabled: false

server:
  image:
    repository: "hashicorp/vault"
    tag: "1.21.4"

  standalone:
    enabled: false

  serviceAccount:
    create: true
    name: "sa-vault-demo"
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::340825716924:role/VaultKMSRole

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: gp2


  ha:
    enabled: true
    replicas: 3
    
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        
        seal "awskms" {
          region     = "ap-south-1"
          kms_key_id = "a8a11064-8dd4-4830-84a2-ca6d1d51fa0b"
        }

        storage "raft" {
          path = "/vault/data"
            retry_join {
              leader_api_addr = "http://vault-helm-0.vault-helm-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-helm-1.vault-helm-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-helm-2.vault-helm-internal:8200"
            }
            autopilot {
              cleanup_dead_servers = "true"
              last_contact_threshold = "200ms"
              max_trailing_logs = 250000
              min_quorum = 3
              server_stabilization_time = "10s"
            }
        }

ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  annotations: 
    service.beta.kubernetes.io/aws-loadbalancer-type: external
