injector:
  enabled: false

server:
  image:
    repository: "hashicorp/vault"
    tag: "1.21.4"

  standalone:
    enabled: false

  serviceAccount:
    create: true
    name: "sa-vault-demo"

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: gp2


  ha:
    enabled: true
    replicas: 3
    
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
        }

ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  annotations: 
    service.beta.kubernetes.io/aws-loadbalancer-type: external 
